name: wasm

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Add nightly toolchain
        run: rustup component add rust-src --toolchain nightly
      - name: Install just
        run: cargo install just
      - name: Build
        run: just build-wasm
